name: tmchip_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  camera: ^0.11.3
  image_picker: ^1.2.1
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/font/
    - assets/icons/
    # - assets/bitmojis/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/font/AvenirNextLTPro-Regular.otf
          weight: 400
        - asset: assets/font/AvenirNextLTPro-It.otf
          style: italic
        - asset: assets/font/AvenirNextLTPro-Demi.otf
          weight: 500
        - asset: assets/font/AvenirNextLTPro-DemiCn.otf
          weight: 500
        - asset: assets/font/AvenirNextLTPro-Bold.otf
          weight: 700
        - asset: assets/font/AvenirNextLTPro-BoldCn.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
